services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecomdb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
      - 'POSTGRES_USER=zisan'
    ports:
      - '5433:5432'
